// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	category "github.com/riyanamanda/helpdesk-backend/internal/category"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepository is an autogenerated mock type for the CategoryRepository type
type CategoryRepository struct {
	mock.Mock
}

type CategoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CategoryRepository) EXPECT() *CategoryRepository_Expecter {
	return &CategoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *CategoryRepository) Create(ctx context.Context, _a1 *category.Category) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *category.Category) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CategoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *category.Category
func (_e *CategoryRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *CategoryRepository_Create_Call {
	return &CategoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *CategoryRepository_Create_Call) Run(run func(ctx context.Context, _a1 *category.Category)) *CategoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*category.Category))
	})
	return _c
}

func (_c *CategoryRepository_Create_Call) Return(_a0 error) *CategoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Create_Call) RunAndReturn(run func(context.Context, *category.Category) error) *CategoryRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CategoryRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CategoryRepository_Expecter) Delete(ctx interface{}, id interface{}) *CategoryRepository_Delete_Call {
	return &CategoryRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *CategoryRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *CategoryRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CategoryRepository_Delete_Call) Return(_a0 error) *CategoryRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *CategoryRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, params
func (_m *CategoryRepository) GetAll(ctx context.Context, params category.GetCategoryParams) ([]category.Category, int64, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []category.Category
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, category.GetCategoryParams) ([]category.Category, int64, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, category.GetCategoryParams) []category.Category); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, category.GetCategoryParams) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, category.GetCategoryParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CategoryRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type CategoryRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - params category.GetCategoryParams
func (_e *CategoryRepository_Expecter) GetAll(ctx interface{}, params interface{}) *CategoryRepository_GetAll_Call {
	return &CategoryRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, params)}
}

func (_c *CategoryRepository_GetAll_Call) Run(run func(ctx context.Context, params category.GetCategoryParams)) *CategoryRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(category.GetCategoryParams))
	})
	return _c
}

func (_c *CategoryRepository_GetAll_Call) Return(_a0 []category.Category, _a1 int64, _a2 error) *CategoryRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *CategoryRepository_GetAll_Call) RunAndReturn(run func(context.Context, category.GetCategoryParams) ([]category.Category, int64, error)) *CategoryRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CategoryRepository) GetByID(ctx context.Context, id int64) (*category.Category, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *category.Category
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*category.Category, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *category.Category); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CategoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type CategoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *CategoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *CategoryRepository_GetByID_Call {
	return &CategoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *CategoryRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *CategoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *CategoryRepository_GetByID_Call) Return(_a0 *category.Category, _a1 error) *CategoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CategoryRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*category.Category, error)) *CategoryRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *CategoryRepository) Update(ctx context.Context, id int64, _a2 *category.Category) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *category.Category) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CategoryRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CategoryRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - _a2 *category.Category
func (_e *CategoryRepository_Expecter) Update(ctx interface{}, id interface{}, _a2 interface{}) *CategoryRepository_Update_Call {
	return &CategoryRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, _a2)}
}

func (_c *CategoryRepository_Update_Call) Run(run func(ctx context.Context, id int64, _a2 *category.Category)) *CategoryRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*category.Category))
	})
	return _c
}

func (_c *CategoryRepository_Update_Call) Return(_a0 error) *CategoryRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CategoryRepository_Update_Call) RunAndReturn(run func(context.Context, int64, *category.Category) error) *CategoryRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCategoryRepository creates a new instance of CategoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepository {
	mock := &CategoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
