// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dashboard "github.com/riyanamanda/helpdesk-backend/internal/dashboard"

	mock "github.com/stretchr/testify/mock"
)

type DashboardRepository struct {
	mock.Mock
}

type DashboardRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DashboardRepository) EXPECT() *DashboardRepository_Expecter {
	return &DashboardRepository_Expecter{mock: &_m.Mock}
}

func (_m *DashboardRepository) GetSummary(ctx context.Context) (dashboard.SummaryResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 dashboard.SummaryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dashboard.SummaryResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dashboard.SummaryResponse); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dashboard.SummaryResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type DashboardRepository_GetSummary_Call struct {
	*mock.Call
}

func (_e *DashboardRepository_Expecter) GetSummary(ctx interface{}) *DashboardRepository_GetSummary_Call {
	return &DashboardRepository_GetSummary_Call{Call: _e.mock.On("GetSummary", ctx)}
}

func (_c *DashboardRepository_GetSummary_Call) Run(run func(ctx context.Context)) *DashboardRepository_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DashboardRepository_GetSummary_Call) Return(_a0 dashboard.SummaryResponse, _a1 error) *DashboardRepository_GetSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardRepository_GetSummary_Call) RunAndReturn(run func(context.Context) (dashboard.SummaryResponse, error)) *DashboardRepository_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *DashboardRepository) GetRecentTickets(ctx context.Context) ([]dashboard.RecentTicket, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentTickets")
	}

	var r0 []dashboard.RecentTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]dashboard.RecentTicket, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []dashboard.RecentTicket); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dashboard.RecentTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type DashboardRepository_GetRecentTickets_Call struct {
	*mock.Call
}

func (_e *DashboardRepository_Expecter) GetRecentTickets(ctx interface{}) *DashboardRepository_GetRecentTickets_Call {
	return &DashboardRepository_GetRecentTickets_Call{Call: _e.mock.On("GetRecentTickets", ctx)}
}

func (_c *DashboardRepository_GetRecentTickets_Call) Run(run func(ctx context.Context)) *DashboardRepository_GetRecentTickets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DashboardRepository_GetRecentTickets_Call) Return(_a0 []dashboard.RecentTicket, _a1 error) *DashboardRepository_GetRecentTickets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardRepository_GetRecentTickets_Call) RunAndReturn(run func(context.Context) ([]dashboard.RecentTicket, error)) *DashboardRepository_GetRecentTickets_Call {
	_c.Call.Return(run)
	return _c
}

func NewDashboardRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardRepository {
	mock := &DashboardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
