// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	ticket "github.com/riyanamanda/helpdesk-backend/internal/ticket"

	uuid "github.com/google/uuid"
)

type TicketRepository struct {
	mock.Mock
}

type TicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketRepository) EXPECT() *TicketRepository_Expecter {
	return &TicketRepository_Expecter{mock: &_m.Mock}
}

func (_m *TicketRepository) Begin(ctx context.Context) (ticket.TicketTx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 ticket.TicketTx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (ticket.TicketTx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) ticket.TicketTx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ticket.TicketTx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type TicketRepository_Begin_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) Begin(ctx interface{}) *TicketRepository_Begin_Call {
	return &TicketRepository_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *TicketRepository_Begin_Call) Run(run func(ctx context.Context)) *TicketRepository_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TicketRepository_Begin_Call) Return(_a0 ticket.TicketTx, _a1 error) *TicketRepository_Begin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_Begin_Call) RunAndReturn(run func(context.Context) (ticket.TicketTx, error)) *TicketRepository_Begin_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketRepository) Assign(ctx context.Context, ticketID int64, userID uuid.UUID) error {
	ret := _m.Called(ctx, ticketID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = rf(ctx, ticketID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketRepository_Assign_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) Assign(ctx interface{}, ticketID interface{}, userID interface{}) *TicketRepository_Assign_Call {
	return &TicketRepository_Assign_Call{Call: _e.mock.On("Assign", ctx, ticketID, userID)}
}

func (_c *TicketRepository_Assign_Call) Run(run func(ctx context.Context, ticketID int64, userID uuid.UUID)) *TicketRepository_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TicketRepository_Assign_Call) Return(_a0 error) *TicketRepository_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_Assign_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) error) *TicketRepository_Assign_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketRepository) CloseTicket(ctx context.Context, ticketID int64, userID uuid.UUID) error {
	ret := _m.Called(ctx, ticketID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CloseTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = rf(ctx, ticketID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketRepository_CloseTicket_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) CloseTicket(ctx interface{}, ticketID interface{}, userID interface{}) *TicketRepository_CloseTicket_Call {
	return &TicketRepository_CloseTicket_Call{Call: _e.mock.On("CloseTicket", ctx, ticketID, userID)}
}

func (_c *TicketRepository_CloseTicket_Call) Run(run func(ctx context.Context, ticketID int64, userID uuid.UUID)) *TicketRepository_CloseTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TicketRepository_CloseTicket_Call) Return(_a0 error) *TicketRepository_CloseTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_CloseTicket_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) error) *TicketRepository_CloseTicket_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketRepository) GetAll(ctx context.Context, params ticket.GetTicketParams) ([]ticket.TicketProjection, int64, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []ticket.TicketProjection
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.GetTicketParams) ([]ticket.TicketProjection, int64, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ticket.GetTicketParams) []ticket.TicketProjection); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ticket.TicketProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ticket.GetTicketParams) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ticket.GetTicketParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

type TicketRepository_GetAll_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) GetAll(ctx interface{}, params interface{}) *TicketRepository_GetAll_Call {
	return &TicketRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, params)}
}

func (_c *TicketRepository_GetAll_Call) Run(run func(ctx context.Context, params ticket.GetTicketParams)) *TicketRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ticket.GetTicketParams))
	})
	return _c
}

func (_c *TicketRepository_GetAll_Call) Return(_a0 []ticket.TicketProjection, _a1 int64, _a2 error) *TicketRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TicketRepository_GetAll_Call) RunAndReturn(run func(context.Context, ticket.GetTicketParams) ([]ticket.TicketProjection, int64, error)) *TicketRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketRepository) GetAttachmentsByTicketID(ctx context.Context, ticketID int64) (*[]ticket.TicketAttachmentProjection, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachmentsByTicketID")
	}

	var r0 *[]ticket.TicketAttachmentProjection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*[]ticket.TicketAttachmentProjection, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *[]ticket.TicketAttachmentProjection); ok {
		r0 = rf(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]ticket.TicketAttachmentProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type TicketRepository_GetAttachmentsByTicketID_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) GetAttachmentsByTicketID(ctx interface{}, ticketID interface{}) *TicketRepository_GetAttachmentsByTicketID_Call {
	return &TicketRepository_GetAttachmentsByTicketID_Call{Call: _e.mock.On("GetAttachmentsByTicketID", ctx, ticketID)}
}

func (_c *TicketRepository_GetAttachmentsByTicketID_Call) Run(run func(ctx context.Context, ticketID int64)) *TicketRepository_GetAttachmentsByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TicketRepository_GetAttachmentsByTicketID_Call) Return(_a0 *[]ticket.TicketAttachmentProjection, _a1 error) *TicketRepository_GetAttachmentsByTicketID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_GetAttachmentsByTicketID_Call) RunAndReturn(run func(context.Context, int64) (*[]ticket.TicketAttachmentProjection, error)) *TicketRepository_GetAttachmentsByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketRepository) GetByID(ctx context.Context, id int64) (*ticket.TicketProjection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ticket.TicketProjection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*ticket.TicketProjection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *ticket.TicketProjection); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.TicketProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type TicketRepository_GetByID_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TicketRepository_GetByID_Call {
	return &TicketRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TicketRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *TicketRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TicketRepository_GetByID_Call) Return(_a0 *ticket.TicketProjection, _a1 error) *TicketRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*ticket.TicketProjection, error)) *TicketRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketRepository) UpdatePriority(ctx context.Context, ticketID int64, priority ticket.TicketPriority) error {
	ret := _m.Called(ctx, ticketID, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ticket.TicketPriority) error); ok {
		r0 = rf(ctx, ticketID, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketRepository_UpdatePriority_Call struct {
	*mock.Call
}

func (_e *TicketRepository_Expecter) UpdatePriority(ctx interface{}, ticketID interface{}, priority interface{}) *TicketRepository_UpdatePriority_Call {
	return &TicketRepository_UpdatePriority_Call{Call: _e.mock.On("UpdatePriority", ctx, ticketID, priority)}
}

func (_c *TicketRepository_UpdatePriority_Call) Run(run func(ctx context.Context, ticketID int64, priority ticket.TicketPriority)) *TicketRepository_UpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(ticket.TicketPriority))
	})
	return _c
}

func (_c *TicketRepository_UpdatePriority_Call) Return(_a0 error) *TicketRepository_UpdatePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_UpdatePriority_Call) RunAndReturn(run func(context.Context, int64, ticket.TicketPriority) error) *TicketRepository_UpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

func NewTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepository {
	mock := &TicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
