// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	sqlx "github.com/jmoiron/sqlx"
	mock "github.com/stretchr/testify/mock"

	ticket "github.com/riyanamanda/helpdesk-backend/internal/ticket"

	uuid "github.com/google/uuid"
)

// TicketRepository is an autogenerated mock type for the TicketRepository type
type TicketRepository struct {
	mock.Mock
}

type TicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketRepository) EXPECT() *TicketRepository_Expecter {
	return &TicketRepository_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function with given fields: ctx, ticketID, userID
func (_m *TicketRepository) Assign(ctx context.Context, ticketID int64, userID uuid.UUID) error {
	ret := _m.Called(ctx, ticketID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = rf(ctx, ticketID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TicketRepository_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type TicketRepository_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int64
//   - userID uuid.UUID
func (_e *TicketRepository_Expecter) Assign(ctx interface{}, ticketID interface{}, userID interface{}) *TicketRepository_Assign_Call {
	return &TicketRepository_Assign_Call{Call: _e.mock.On("Assign", ctx, ticketID, userID)}
}

func (_c *TicketRepository_Assign_Call) Run(run func(ctx context.Context, ticketID int64, userID uuid.UUID)) *TicketRepository_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TicketRepository_Assign_Call) Return(_a0 error) *TicketRepository_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_Assign_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) error) *TicketRepository_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// CloseTicket provides a mock function with given fields: ctx, ticketID, userID
func (_m *TicketRepository) CloseTicket(ctx context.Context, ticketID int64, userID uuid.UUID) error {
	ret := _m.Called(ctx, ticketID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CloseTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID) error); ok {
		r0 = rf(ctx, ticketID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TicketRepository_CloseTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseTicket'
type TicketRepository_CloseTicket_Call struct {
	*mock.Call
}

// CloseTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int64
//   - userID uuid.UUID
func (_e *TicketRepository_Expecter) CloseTicket(ctx interface{}, ticketID interface{}, userID interface{}) *TicketRepository_CloseTicket_Call {
	return &TicketRepository_CloseTicket_Call{Call: _e.mock.On("CloseTicket", ctx, ticketID, userID)}
}

func (_c *TicketRepository_CloseTicket_Call) Run(run func(ctx context.Context, ticketID int64, userID uuid.UUID)) *TicketRepository_CloseTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *TicketRepository_CloseTicket_Call) Return(_a0 error) *TicketRepository_CloseTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_CloseTicket_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID) error) *TicketRepository_CloseTicket_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, tx, _a2
func (_m *TicketRepository) Create(ctx context.Context, tx *sqlx.Tx, _a2 ticket.Ticket) (int64, error) {
	ret := _m.Called(ctx, tx, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, ticket.Ticket) (int64, error)); ok {
		return rf(ctx, tx, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, ticket.Ticket) int64); ok {
		r0 = rf(ctx, tx, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, ticket.Ticket) error); ok {
		r1 = rf(ctx, tx, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TicketRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - _a2 ticket.Ticket
func (_e *TicketRepository_Expecter) Create(ctx interface{}, tx interface{}, _a2 interface{}) *TicketRepository_Create_Call {
	return &TicketRepository_Create_Call{Call: _e.mock.On("Create", ctx, tx, _a2)}
}

func (_c *TicketRepository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, _a2 ticket.Ticket)) *TicketRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(ticket.Ticket))
	})
	return _c
}

func (_c *TicketRepository_Create_Call) Return(_a0 int64, _a1 error) *TicketRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, ticket.Ticket) (int64, error)) *TicketRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAttachment provides a mock function with given fields: ctx, tx, attachment
func (_m *TicketRepository) CreateAttachment(ctx context.Context, tx *sqlx.Tx, attachment ticket.TicketAttachment) error {
	ret := _m.Called(ctx, tx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, ticket.TicketAttachment) error); ok {
		r0 = rf(ctx, tx, attachment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TicketRepository_CreateAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAttachment'
type TicketRepository_CreateAttachment_Call struct {
	*mock.Call
}

// CreateAttachment is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - attachment ticket.TicketAttachment
func (_e *TicketRepository_Expecter) CreateAttachment(ctx interface{}, tx interface{}, attachment interface{}) *TicketRepository_CreateAttachment_Call {
	return &TicketRepository_CreateAttachment_Call{Call: _e.mock.On("CreateAttachment", ctx, tx, attachment)}
}

func (_c *TicketRepository_CreateAttachment_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, attachment ticket.TicketAttachment)) *TicketRepository_CreateAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(ticket.TicketAttachment))
	})
	return _c
}

func (_c *TicketRepository_CreateAttachment_Call) Return(_a0 error) *TicketRepository_CreateAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_CreateAttachment_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, ticket.TicketAttachment) error) *TicketRepository_CreateAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, params
func (_m *TicketRepository) GetAll(ctx context.Context, params ticket.GetTicketParams) ([]ticket.TicketProjection, int64, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []ticket.TicketProjection
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.GetTicketParams) ([]ticket.TicketProjection, int64, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ticket.GetTicketParams) []ticket.TicketProjection); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ticket.TicketProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ticket.GetTicketParams) int64); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ticket.GetTicketParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TicketRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type TicketRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - params ticket.GetTicketParams
func (_e *TicketRepository_Expecter) GetAll(ctx interface{}, params interface{}) *TicketRepository_GetAll_Call {
	return &TicketRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, params)}
}

func (_c *TicketRepository_GetAll_Call) Run(run func(ctx context.Context, params ticket.GetTicketParams)) *TicketRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ticket.GetTicketParams))
	})
	return _c
}

func (_c *TicketRepository_GetAll_Call) Return(_a0 []ticket.TicketProjection, _a1 int64, _a2 error) *TicketRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TicketRepository_GetAll_Call) RunAndReturn(run func(context.Context, ticket.GetTicketParams) ([]ticket.TicketProjection, int64, error)) *TicketRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttachmentsByTicketID provides a mock function with given fields: ctx, ticketID
func (_m *TicketRepository) GetAttachmentsByTicketID(ctx context.Context, ticketID int64) (*[]ticket.TicketAttachmentProjection, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachmentsByTicketID")
	}

	var r0 *[]ticket.TicketAttachmentProjection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*[]ticket.TicketAttachmentProjection, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *[]ticket.TicketAttachmentProjection); ok {
		r0 = rf(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]ticket.TicketAttachmentProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketRepository_GetAttachmentsByTicketID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttachmentsByTicketID'
type TicketRepository_GetAttachmentsByTicketID_Call struct {
	*mock.Call
}

// GetAttachmentsByTicketID is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int64
func (_e *TicketRepository_Expecter) GetAttachmentsByTicketID(ctx interface{}, ticketID interface{}) *TicketRepository_GetAttachmentsByTicketID_Call {
	return &TicketRepository_GetAttachmentsByTicketID_Call{Call: _e.mock.On("GetAttachmentsByTicketID", ctx, ticketID)}
}

func (_c *TicketRepository_GetAttachmentsByTicketID_Call) Run(run func(ctx context.Context, ticketID int64)) *TicketRepository_GetAttachmentsByTicketID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TicketRepository_GetAttachmentsByTicketID_Call) Return(_a0 *[]ticket.TicketAttachmentProjection, _a1 error) *TicketRepository_GetAttachmentsByTicketID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_GetAttachmentsByTicketID_Call) RunAndReturn(run func(context.Context, int64) (*[]ticket.TicketAttachmentProjection, error)) *TicketRepository_GetAttachmentsByTicketID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TicketRepository) GetByID(ctx context.Context, id int64) (*ticket.TicketProjection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *ticket.TicketProjection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*ticket.TicketProjection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *ticket.TicketProjection); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ticket.TicketProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TicketRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type TicketRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *TicketRepository_Expecter) GetByID(ctx interface{}, id interface{}) *TicketRepository_GetByID_Call {
	return &TicketRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *TicketRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *TicketRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *TicketRepository_GetByID_Call) Return(_a0 *ticket.TicketProjection, _a1 error) *TicketRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*ticket.TicketProjection, error)) *TicketRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePriority provides a mock function with given fields: ctx, ticketID, priority
func (_m *TicketRepository) UpdatePriority(ctx context.Context, ticketID int64, priority ticket.TicketPriority) error {
	ret := _m.Called(ctx, ticketID, priority)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePriority")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, ticket.TicketPriority) error); ok {
		r0 = rf(ctx, ticketID, priority)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TicketRepository_UpdatePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePriority'
type TicketRepository_UpdatePriority_Call struct {
	*mock.Call
}

// UpdatePriority is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID int64
//   - priority ticket.TicketPriority
func (_e *TicketRepository_Expecter) UpdatePriority(ctx interface{}, ticketID interface{}, priority interface{}) *TicketRepository_UpdatePriority_Call {
	return &TicketRepository_UpdatePriority_Call{Call: _e.mock.On("UpdatePriority", ctx, ticketID, priority)}
}

func (_c *TicketRepository_UpdatePriority_Call) Run(run func(ctx context.Context, ticketID int64, priority ticket.TicketPriority)) *TicketRepository_UpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(ticket.TicketPriority))
	})
	return _c
}

func (_c *TicketRepository_UpdatePriority_Call) Return(_a0 error) *TicketRepository_UpdatePriority_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_UpdatePriority_Call) RunAndReturn(run func(context.Context, int64, ticket.TicketPriority) error) *TicketRepository_UpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResolution provides a mock function with given fields: ctx, tx, ticketID, userID, resolution
func (_m *TicketRepository) UpdateResolution(ctx context.Context, tx *sqlx.Tx, ticketID int64, userID uuid.UUID, resolution string) error {
	ret := _m.Called(ctx, tx, ticketID, userID, resolution)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResolution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int64, uuid.UUID, string) error); ok {
		r0 = rf(ctx, tx, ticketID, userID, resolution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TicketRepository_UpdateResolution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResolution'
type TicketRepository_UpdateResolution_Call struct {
	*mock.Call
}

// UpdateResolution is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - ticketID int64
//   - userID uuid.UUID
//   - resolution string
func (_e *TicketRepository_Expecter) UpdateResolution(ctx interface{}, tx interface{}, ticketID interface{}, userID interface{}, resolution interface{}) *TicketRepository_UpdateResolution_Call {
	return &TicketRepository_UpdateResolution_Call{Call: _e.mock.On("UpdateResolution", ctx, tx, ticketID, userID, resolution)}
}

func (_c *TicketRepository_UpdateResolution_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, ticketID int64, userID uuid.UUID, resolution string)) *TicketRepository_UpdateResolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(int64), args[3].(uuid.UUID), args[4].(string))
	})
	return _c
}

func (_c *TicketRepository_UpdateResolution_Call) Return(_a0 error) *TicketRepository_UpdateResolution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketRepository_UpdateResolution_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, int64, uuid.UUID, string) error) *TicketRepository_UpdateResolution_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicketRepository creates a new instance of TicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepository {
	mock := &TicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
