// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ticket "github.com/riyanamanda/helpdesk-backend/internal/ticket"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

type TicketTx struct {
	mock.Mock
}

type TicketTx_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketTx) EXPECT() *TicketTx_Expecter {
	return &TicketTx_Expecter{mock: &_m.Mock}
}

func (_m *TicketTx) Create(ctx context.Context, t ticket.Ticket) (int64, error) {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.Ticket) (int64, error)); ok {
		return rf(ctx, t)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ticket.Ticket) int64); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, ticket.Ticket) error); ok {
		r1 = rf(ctx, t)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type TicketTx_Create_Call struct {
	*mock.Call
}

func (_e *TicketTx_Expecter) Create(ctx interface{}, t interface{}) *TicketTx_Create_Call {
	return &TicketTx_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *TicketTx_Create_Call) Run(run func(ctx context.Context, t ticket.Ticket)) *TicketTx_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ticket.Ticket))
	})
	return _c
}

func (_c *TicketTx_Create_Call) Return(_a0 int64, _a1 error) *TicketTx_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TicketTx_Create_Call) RunAndReturn(run func(context.Context, ticket.Ticket) (int64, error)) *TicketTx_Create_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketTx) CreateAttachment(ctx context.Context, attachment ticket.TicketAttachment) error {
	ret := _m.Called(ctx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for CreateAttachment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.TicketAttachment) error); ok {
		r0 = rf(ctx, attachment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketTx_CreateAttachment_Call struct {
	*mock.Call
}

func (_e *TicketTx_Expecter) CreateAttachment(ctx interface{}, attachment interface{}) *TicketTx_CreateAttachment_Call {
	return &TicketTx_CreateAttachment_Call{Call: _e.mock.On("CreateAttachment", ctx, attachment)}
}

func (_c *TicketTx_CreateAttachment_Call) Run(run func(ctx context.Context, attachment ticket.TicketAttachment)) *TicketTx_CreateAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ticket.TicketAttachment))
	})
	return _c
}

func (_c *TicketTx_CreateAttachment_Call) Return(_a0 error) *TicketTx_CreateAttachment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketTx_CreateAttachment_Call) RunAndReturn(run func(context.Context, ticket.TicketAttachment) error) *TicketTx_CreateAttachment_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketTx) UpdateResolution(ctx context.Context, ticketID int64, userID uuid.UUID, resolution string) error {
	ret := _m.Called(ctx, ticketID, userID, resolution)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResolution")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, uuid.UUID, string) error); ok {
		r0 = rf(ctx, ticketID, userID, resolution)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketTx_UpdateResolution_Call struct {
	*mock.Call
}

func (_e *TicketTx_Expecter) UpdateResolution(ctx interface{}, ticketID interface{}, userID interface{}, resolution interface{}) *TicketTx_UpdateResolution_Call {
	return &TicketTx_UpdateResolution_Call{Call: _e.mock.On("UpdateResolution", ctx, ticketID, userID, resolution)}
}

func (_c *TicketTx_UpdateResolution_Call) Run(run func(ctx context.Context, ticketID int64, userID uuid.UUID, resolution string)) *TicketTx_UpdateResolution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *TicketTx_UpdateResolution_Call) Return(_a0 error) *TicketTx_UpdateResolution_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketTx_UpdateResolution_Call) RunAndReturn(run func(context.Context, int64, uuid.UUID, string) error) *TicketTx_UpdateResolution_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketTx) Commit() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketTx_Commit_Call struct {
	*mock.Call
}

func (_e *TicketTx_Expecter) Commit() *TicketTx_Commit_Call {
	return &TicketTx_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *TicketTx_Commit_Call) Run(run func()) *TicketTx_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) { run() })
	return _c
}

func (_c *TicketTx_Commit_Call) Return(_a0 error) *TicketTx_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketTx_Commit_Call) RunAndReturn(run func() error) *TicketTx_Commit_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *TicketTx) Rollback() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type TicketTx_Rollback_Call struct {
	*mock.Call
}

func (_e *TicketTx_Expecter) Rollback() *TicketTx_Rollback_Call {
	return &TicketTx_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *TicketTx_Rollback_Call) Run(run func()) *TicketTx_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) { run() })
	return _c
}

func (_c *TicketTx_Rollback_Call) Return(_a0 error) *TicketTx_Rollback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TicketTx_Rollback_Call) RunAndReturn(run func() error) *TicketTx_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

func NewTicketTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketTx {
	mock := &TicketTx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
