// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	ticket "github.com/riyanamanda/helpdesk-backend/internal/ticket"
	mock "github.com/stretchr/testify/mock"
)

// TicketRepository is an autogenerated mock type for the TicketRepository type
type TicketRepository struct {
	mock.Mock
}

type TicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TicketRepository) EXPECT() *TicketRepository_Expecter {
	return &TicketRepository_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx, params
func (_m *TicketRepository) GetAll(ctx context.Context, params ticket.GetTicketParams) ([]ticket.Ticket, int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []ticket.Ticket
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, ticket.GetTicketParams) ([]ticket.Ticket, int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ticket.GetTicketParams) []ticket.Ticket); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ticket.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ticket.GetTicketParams) int); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, ticket.GetTicketParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TicketRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type TicketRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - params ticket.GetTicketParams
func (_e *TicketRepository_Expecter) GetAll(ctx interface{}, params interface{}) *TicketRepository_GetAll_Call {
	return &TicketRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, params)}
}

func (_c *TicketRepository_GetAll_Call) Run(run func(ctx context.Context, params ticket.GetTicketParams)) *TicketRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ticket.GetTicketParams))
	})
	return _c
}

func (_c *TicketRepository_GetAll_Call) Return(_a0 []ticket.Ticket, _a1 int, _a2 error) *TicketRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TicketRepository_GetAll_Call) RunAndReturn(run func(context.Context, ticket.GetTicketParams) ([]ticket.Ticket, int, error)) *TicketRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewTicketRepository creates a new instance of TicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TicketRepository {
	mock := &TicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
