// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	user "github.com/riyanamanda/helpdesk-backend/internal/user"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

type ProfileRepository struct {
	mock.Mock
}

type ProfileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileRepository) EXPECT() *ProfileRepository_Expecter {
	return &ProfileRepository_Expecter{mock: &_m.Mock}
}

func (_m *ProfileRepository) GetByID(ctx context.Context, id uuid.UUID) (*user.UserProjection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.UserProjection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*user.UserProjection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *user.UserProjection); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.UserProjection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type ProfileRepository_GetByID_Call struct {
	*mock.Call
}

func (_e *ProfileRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ProfileRepository_GetByID_Call {
	return &ProfileRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ProfileRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ProfileRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ProfileRepository_GetByID_Call) Return(_a0 *user.UserProjection, _a1 error) *ProfileRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProfileRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*user.UserProjection, error)) *ProfileRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *ProfileRepository) UpdateProfile(ctx context.Context, id uuid.UUID, name string, phone *string) error {
	ret := _m.Called(ctx, id, name, phone)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *string) error); ok {
		r0 = rf(ctx, id, name, phone)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type ProfileRepository_UpdateProfile_Call struct {
	*mock.Call
}

func (_e *ProfileRepository_Expecter) UpdateProfile(ctx interface{}, id interface{}, name interface{}, phone interface{}) *ProfileRepository_UpdateProfile_Call {
	return &ProfileRepository_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, id, name, phone)}
}

func (_c *ProfileRepository_UpdateProfile_Call) Run(run func(ctx context.Context, id uuid.UUID, name string, phone *string)) *ProfileRepository_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *ProfileRepository_UpdateProfile_Call) Return(_a0 error) *ProfileRepository_UpdateProfile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileRepository_UpdateProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, *string) error) *ProfileRepository_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *ProfileRepository) UpdateAvatar(ctx context.Context, id uuid.UUID, avatarKey string) error {
	ret := _m.Called(ctx, id, avatarKey)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAvatar")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, avatarKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type ProfileRepository_UpdateAvatar_Call struct {
	*mock.Call
}

func (_e *ProfileRepository_Expecter) UpdateAvatar(ctx interface{}, id interface{}, avatarKey interface{}) *ProfileRepository_UpdateAvatar_Call {
	return &ProfileRepository_UpdateAvatar_Call{Call: _e.mock.On("UpdateAvatar", ctx, id, avatarKey)}
}

func (_c *ProfileRepository_UpdateAvatar_Call) Run(run func(ctx context.Context, id uuid.UUID, avatarKey string)) *ProfileRepository_UpdateAvatar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ProfileRepository_UpdateAvatar_Call) Return(_a0 error) *ProfileRepository_UpdateAvatar_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileRepository_UpdateAvatar_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *ProfileRepository_UpdateAvatar_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *ProfileRepository) SetGoogleID(ctx context.Context, id uuid.UUID, googleID string) error {
	ret := _m.Called(ctx, id, googleID)

	if len(ret) == 0 {
		panic("no return value specified for SetGoogleID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, id, googleID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type ProfileRepository_SetGoogleID_Call struct {
	*mock.Call
}

func (_e *ProfileRepository_Expecter) SetGoogleID(ctx interface{}, id interface{}, googleID interface{}) *ProfileRepository_SetGoogleID_Call {
	return &ProfileRepository_SetGoogleID_Call{Call: _e.mock.On("SetGoogleID", ctx, id, googleID)}
}

func (_c *ProfileRepository_SetGoogleID_Call) Run(run func(ctx context.Context, id uuid.UUID, googleID string)) *ProfileRepository_SetGoogleID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *ProfileRepository_SetGoogleID_Call) Return(_a0 error) *ProfileRepository_SetGoogleID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProfileRepository_SetGoogleID_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *ProfileRepository_SetGoogleID_Call {
	_c.Call.Return(run)
	return _c
}

func NewProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRepository {
	mock := &ProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
