// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	division "github.com/riyanamanda/helpdesk-backend/internal/division"
	mock "github.com/stretchr/testify/mock"
)

// DivisionRepository is an autogenerated mock type for the DivisionRepository type
type DivisionRepository struct {
	mock.Mock
}

type DivisionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *DivisionRepository) EXPECT() *DivisionRepository_Expecter {
	return &DivisionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *DivisionRepository) Create(ctx context.Context, _a1 *division.Division) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *division.Division) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type DivisionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *division.Division
func (_e *DivisionRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *DivisionRepository_Create_Call {
	return &DivisionRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *DivisionRepository_Create_Call) Run(run func(ctx context.Context, _a1 *division.Division)) *DivisionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*division.Division))
	})
	return _c
}

func (_c *DivisionRepository_Create_Call) Return(_a0 error) *DivisionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_Create_Call) RunAndReturn(run func(context.Context, *division.Division) error) *DivisionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DivisionRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type DivisionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *DivisionRepository_Expecter) Delete(ctx interface{}, id interface{}) *DivisionRepository_Delete_Call {
	return &DivisionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *DivisionRepository_Delete_Call) Run(run func(ctx context.Context, id int64)) *DivisionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *DivisionRepository_Delete_Call) Return(_a0 error) *DivisionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_Delete_Call) RunAndReturn(run func(context.Context, int64) error) *DivisionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, params
func (_m *DivisionRepository) GetAll(ctx context.Context, params division.GetDivisionParams) ([]division.Division, int, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []division.Division
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, division.GetDivisionParams) ([]division.Division, int, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, division.GetDivisionParams) []division.Division); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]division.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, division.GetDivisionParams) int); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, division.GetDivisionParams) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// DivisionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type DivisionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - params division.GetDivisionParams
func (_e *DivisionRepository_Expecter) GetAll(ctx interface{}, params interface{}) *DivisionRepository_GetAll_Call {
	return &DivisionRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, params)}
}

func (_c *DivisionRepository_GetAll_Call) Run(run func(ctx context.Context, params division.GetDivisionParams)) *DivisionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(division.GetDivisionParams))
	})
	return _c
}

func (_c *DivisionRepository_GetAll_Call) Return(_a0 []division.Division, _a1 int, _a2 error) *DivisionRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *DivisionRepository_GetAll_Call) RunAndReturn(run func(context.Context, division.GetDivisionParams) ([]division.Division, int, error)) *DivisionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *DivisionRepository) GetByID(ctx context.Context, id int64) (*division.Division, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *division.Division
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*division.Division, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *division.Division); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*division.Division)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DivisionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type DivisionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *DivisionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *DivisionRepository_GetByID_Call {
	return &DivisionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *DivisionRepository_GetByID_Call) Run(run func(ctx context.Context, id int64)) *DivisionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *DivisionRepository_GetByID_Call) Return(_a0 *division.Division, _a1 error) *DivisionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DivisionRepository_GetByID_Call) RunAndReturn(run func(context.Context, int64) (*division.Division, error)) *DivisionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *DivisionRepository) Update(ctx context.Context, id int64, _a2 *division.Division) error {
	ret := _m.Called(ctx, id, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *division.Division) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DivisionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type DivisionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - _a2 *division.Division
func (_e *DivisionRepository_Expecter) Update(ctx interface{}, id interface{}, _a2 interface{}) *DivisionRepository_Update_Call {
	return &DivisionRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, _a2)}
}

func (_c *DivisionRepository_Update_Call) Run(run func(ctx context.Context, id int64, _a2 *division.Division)) *DivisionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(*division.Division))
	})
	return _c
}

func (_c *DivisionRepository_Update_Call) Return(_a0 error) *DivisionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DivisionRepository_Update_Call) RunAndReturn(run func(context.Context, int64, *division.Division) error) *DivisionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewDivisionRepository creates a new instance of DivisionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDivisionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DivisionRepository {
	mock := &DivisionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
