// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

type Storage struct {
	mock.Mock
}

type Storage_Expecter struct {
	mock *mock.Mock
}

func (_m *Storage) EXPECT() *Storage_Expecter {
	return &Storage_Expecter{mock: &_m.Mock}
}

func (_m *Storage) Upload(ctx context.Context, key string, reader io.Reader, size int64, contentType string) error {
	ret := _m.Called(ctx, key, reader, size, contentType)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64, string) error); ok {
		r0 = rf(ctx, key, reader, size, contentType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type Storage_Upload_Call struct {
	*mock.Call
}

func (_e *Storage_Expecter) Upload(ctx interface{}, key interface{}, reader interface{}, size interface{}, contentType interface{}) *Storage_Upload_Call {
	return &Storage_Upload_Call{Call: _e.mock.On("Upload", ctx, key, reader, size, contentType)}
}

func (_c *Storage_Upload_Call) Run(run func(ctx context.Context, key string, reader io.Reader, size int64, contentType string)) *Storage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64), args[4].(string))
	})
	return _c
}

func (_c *Storage_Upload_Call) Return(_a0 error) *Storage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64, string) error) *Storage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

func (_m *Storage) Delete(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type Storage_Delete_Call struct {
	*mock.Call
}

func (_e *Storage_Expecter) Delete(ctx interface{}, key interface{}) *Storage_Delete_Call {
	return &Storage_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *Storage_Delete_Call) Run(run func(ctx context.Context, key string)) *Storage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Storage_Delete_Call) Return(_a0 error) *Storage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Storage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *Storage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

func NewStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Storage {
	mock := &Storage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
